CREATE ROLE [dev]
GO
GRANT SELECT, INSERT,UPDATE, DELETE ON Schema ::core TO dev
GO
GRANT SELECT, INSERT,UPDATE, DELETE ON Schema ::[event] TO dev
GO
GRANT SELECT, INSERT,UPDATE, DELETE ON Schema ::geo TO dev
GO
GRANT SELECT, INSERT,UPDATE, DELETE ON Schema ::ref TO dev
GO
GRANT SELECT, INSERT,UPDATE, DELETE ON Schema ::temp TO dev